name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
      - google-compute-engine

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available

      - name: Build JAR file
        run: ./gradlew build
        
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCE_SECRET }}
          
      - name: Copy JAR file to Google Compute Engine
        run: |
          gcloud compute scp build/libs/soprafs23.jar instance-1:~/ \
            --project "sopra-fs23-group-12-server-v2" \
            --zone "us-central1-a"
            
          # SSH into the server and execute commands
          gcloud compute ssh instance-1 \
            --project "sopra-fs23-group-12-server-v2" \
            --zone "us-central1-a" \
            --command "PRODUCTION=true nohup java -jar soprafs23.jar > output.log 2>&1 &"